workflows:

  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Moments
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: ai.simplify.moments
      vars:
          XCODE_WORKSPACE: "memories.xcworkspace"
          XCODE_SCHEME: "memories"
          BUNDLE_ID: "ai.simplify.moments"
          APP_ID: 6468130157
      node: 18.16.0
      xcode: 14.1
      cocoapods: default
    triggering:
        events:
            - push
            - tag
            - pull_request
        branch_patterns:
            - pattern: develop
              include: true
              source: true
    scripts:
      - name: Install dependencies, Expo CLI and eject app
        script: |
          yarn install
          yarn global add expo-cli
          expo eject
      - name: Set Info.plist values
        script: |
          PLIST=$FCI_BUILD_DIR/$XCODE_SCHEME/Info.plist
          PLIST_BUDDY=/usr/libexec/PlistBuddy
          $PLIST_BUDDY -c "Add :ITSAppUsesNonExemptEncryption bool false" $PLIST
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Update CocoaPods
        script: |
          cd ios && pod update
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles --warn-only
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa --archive-flags="-destination 'generic/platform=iOS'" \
          --workspace "$FCI_BUILD_DIR/ios/$XCODE_WORKSPACE" \
          --scheme "$XCODE_SCHEME" \
    artifacts:
        - build/ios/ipa/*.ipa
        - /tmp/xcodebuild_logs/*.log
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - jameskaydev@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration

        # Configuration related to TestFlight (optional)
        # Note: This action is performed during post-processing.
        submit_to_testflight: true
        beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
          - group name 1
          - group name 2

        # Configuration related to App Store (optional)
        # Note: This action is performed during post-processing.
        submit_to_app_store: true